/* =================================================================
   ACTIVE EASTER EGGS — themes that repaint the whole panel
   (body class + overlay + icon set + logo mutation)
   ================================================================= */

export type ActiveEgg = {
  id: string;
  icon: string;
  kind: "theme" | "effect";
  title: { fa: string; en: string };
  subtitle: { fa: string; en: string };
  riddle: { fa: string; en: string };
  keywords: string[];
  /** overlay engine config (only for the 10 new generated themes) */
  overlay?: {
    accent: string;
    accent2: string;
    particles: string[];
    particleCount: number;
    effect: "rain" | "embers" | "scan" | "fog" | "void" | "storm" | "glitch" | "snow" | "spore";
    /** optional accent for the animated logo aura */
    centerGlyph?: string;
    quote: { fa: string; en: string };
    label: string;
  };
  /** logo mutation */
  logo: {
    text: string;          // replacement wordmark
    color: string;         // hex
    font: "edsel" | "mono" | "serif" | "brand";
    anim?: string;         // extra css class
    prefix?: string;       // glyph before
    suffix?: string;       // glyph after
  };
};

export const ACTIVE_EGGS: ActiveEgg[] = [
  /* ---------- ORIGINAL SET (overlays live in their own components) ---------- */
  {
    id: "snow", icon: "❄️", kind: "theme",
    title: { fa: "زمستان قطبی", en: "Arctic Winter" },
    subtitle: { fa: "بارش برف روی کل پنل", en: "Snowfall across the panel" },
    riddle: { fa: "وقتی آسمان یخ می‌بندد و همه‌جا سپید می‌شود، نام آن فصل سرد را در جستجوی اینباندها بنویس.", en: "When the sky freezes and the world turns white — type the name of that cold season in the inbound search." },
    keywords: ["snow", "winter", "برف", "zemestan"],
    logo: { text: "Edsel's", color: "#BAE6FD", font: "edsel", prefix: "❄", anim: "logo-frost" },
  },
  {
    id: "breakingbad", icon: "🧪", kind: "theme",
    title: { fa: "آزمایشگاه هایزنبرگ", en: "Heisenberg Lab" },
    subtitle: { fa: "جدول مندلیف + شیمی", en: "Periodic table + chemistry" },
    riddle: { fa: "بگو نام من چیست؛ معلم شیمی آلبوکرکی که کریستال آبی می‌ساخت.", en: "Say my name — the Albuquerque chemistry teacher who cooked the blue crystal." },
    keywords: ["heisenberg", "breakingbad", "breaking bad", "meth", "bluesky"],
    logo: { text: "Ed", color: "#A3E635", font: "mono", suffix: "sel", anim: "logo-acid" },
  },
  {
    id: "housemd", icon: "🩺", kind: "theme",
    title: { fa: "بیمارستان پرینستون", en: "Princeton–Plainsboro" },
    subtitle: { fa: "تم پزشکی House MD", en: "House MD medical theme" },
    riddle: { fa: "همه دروغ می‌گویند؛ آن بیماری خودایمنی که دکتر لنگ همیشه ردش می‌کند چه نام دارد؟", en: "Everybody lies. Name the autoimmune disease the limping doctor always rules out." },
    keywords: ["lupus", "house", "housemd", "vicodin", "everybody lies"],
    logo: { text: "Edsel's", color: "#38BDF8", font: "edsel", prefix: "✚", anim: "logo-pulse-med" },
  },
  {
    id: "watchdogs", icon: "📱", kind: "theme",
    title: { fa: "شبکه‌ی ctOS", en: "ctOS Network" },
    subtitle: { fa: "تم هکری Watch Dogs", en: "Watch Dogs hacker theme" },
    riddle: { fa: "سیستم‌عامل نظارتی که کل شیکاگو را می‌بلعد و آیدین پیرس آن را هک می‌کند.", en: "The surveillance operating system swallowing all of Chicago, hacked by Aiden Pearce." },
    keywords: ["ctos", "watchdogs", "watch dogs", "aiden", "dedsec", "pearce"],
    logo: { text: "3ds3l's", color: "#22D3EE", font: "mono", anim: "logo-glitch" },
  },
  {
    id: "you", icon: "🩸", kind: "theme",
    title: { fa: "سریال YOU", en: "YOU Series" },
    subtitle: { fa: "من گرگ تو هستم", en: "I wolf you" },
    riddle: { fa: "کتاب‌فروشی که از پشت قفسه‌ها تماشا می‌کند و در قفس شیشه‌ای عشق می‌ورزد.", en: "The bookstore manager who watches from behind the shelves and loves inside a glass cage." },
    keywords: ["joe", "goldberg", "beck", "iwolfyou"],
    logo: { text: "Edsel's", color: "#F43F5E", font: "serif", suffix: "❤", anim: "logo-bleed" },
  },
  {
    id: "mentalist", icon: "☕", kind: "theme",
    title: { fa: "منتالیست", en: "The Mentalist" },
    subtitle: { fa: "رد جان اینجاست", en: "Red John was here" },
    riddle: { fa: "صورتک خندان خونین روی دیوار، یا مشاور موبلوندی که چای می‌نوشد و ذهن می‌خواند.", en: "The bloody smiley on the wall, or the blond consultant who drinks tea and reads minds." },
    keywords: ["jane", "patrick", "redjohn", "red john", "cbi"],
    logo: { text: "Edsel's", color: "#EF4444", font: "serif", suffix: "☺", anim: "logo-smile" },
  },
  {
    id: "residentevil", icon: "🧟", kind: "theme",
    title: { fa: "رزیدنت اویل", en: "Resident Evil" },
    subtitle: { fa: "سایه‌ی آلبرت وسکر", en: "Albert Wesker's shadow" },
    riddle: { fa: "شرکت دارویی چتردار که ویروس T را ساخت و راکون‌سیتی را بلعید.", en: "The umbrella-logoed pharma giant that engineered the T-Virus and devoured Raccoon City." },
    keywords: ["umbrella", "zombie", "wesker", "tvirus", "raccoon"],
    logo: { text: "Edsel's", color: "#22C55E", font: "mono", prefix: "☣", anim: "logo-infect" },
  },
  {
    id: "radiohead", icon: "📻", kind: "theme",
    title: { fa: "رادیوهد", en: "Radiohead" },
    subtitle: { fa: "اندروید پارانوئید", en: "Paranoid Android" },
    riddle: { fa: "گروهی از آکسفوردشر که خواند: من یک عوضی‌ام، اینجا جای من نیست.", en: "The Oxfordshire band that sang: I'm a creep, I don't belong here." },
    keywords: ["creep", "radiohead", "thomyorke", "okcomputer"],
    logo: { text: "Edsel's", color: "#CBD5E1", font: "mono", anim: "logo-static" },
  },
  {
    id: "alanwake", icon: "🔦", kind: "theme",
    title: { fa: "آلن ویک", en: "Alan Wake" },
    subtitle: { fa: "حضور تاریکی", en: "The Dark Presence" },
    riddle: { fa: "نویسنده‌ی رمان جنایی در برایت فالز که با چراغ‌قوه تاریکی را عقب می‌راند.", en: "The thriller novelist in Bright Falls who pushes back the darkness with a flashlight." },
    keywords: ["alan", "wake", "brightfalls", "darkpresence"],
    logo: { text: "Edsel's", color: "#FFFFFF", font: "serif", anim: "logo-flicker" },
  },
  {
    id: "negan", icon: "🦇", kind: "theme",
    title: { fa: "نیگان (واکینگ دد)", en: "Negan (TWD)" },
    subtitle: { fa: "لوسیل تشنه است", en: "Lucille is thirsty" },
    riddle: { fa: "خوک کوچولو، خوک کوچولو... رهبر ناجیان و چوب بیسبال سیم‌خارداری‌اش.", en: "Little pig, little pig... The leader of the Saviors and his barbed-wire bat." },
    keywords: ["negan", "lucille", "saviors", "littlepig"],
    logo: { text: "Edsel's", color: "#DC2626", font: "brand", suffix: "🩸", anim: "logo-swing" },
  },
  {
    id: "edward", icon: "✂️", kind: "theme",
    title: { fa: "ادوارد دست‌قیچی", en: "Edward Scissorhands" },
    subtitle: { fa: "برف و قیچی", en: "Snow and scissors" },
    riddle: { fa: "آفریده‌ی ناتمام تیم برتون که دستانش تیغه‌اند و از یخ، فرشته می‌تراشد.", en: "Tim Burton's unfinished creation whose hands are blades, carving angels out of ice." },
    keywords: ["edward", "scissorhands", "burton", "kim"],
    logo: { text: "Edsel's", color: "#E2E8F0", font: "serif", prefix: "✂", anim: "logo-snip" },
  },
  {
    id: "rustcohle", icon: "🌀", kind: "theme",
    title: { fa: "راستین کوهل · کارآگاه حقیقی", en: "Rustin Cohle · True Detective" },
    subtitle: { fa: "زمان یک دایره‌ی مسطح است", en: "Time is a flat circle" },
    riddle: { fa: "کارآگاه بدبین فصل اول در مرداب‌های لوئیزیانا؛ ستاره‌ها، مارپیچ کارکوسا و زمانی که بارها تکرار می‌شود.", en: "The season-one nihilist in the Louisiana marshes: stars, Carcosa's spiral, and time repeating forever." },
    keywords: ["rustcohle", "rustincohle", "true detective", "truedetective", "carcosa", "yellowking", "راست کول"],
    logo: { text: "Edsel's", color: "#D6B56D", font: "serif", prefix: "🌀", suffix: "//1995", anim: "logo-flat-circle" },
  },
  {
    id: "matrix", icon: "💊", kind: "effect",
    title: { fa: "ماتریکس", en: "The Matrix" },
    subtitle: { fa: "بارش کد سبز", en: "Green code rain" },
    riddle: { fa: "قرص قرمز یا قرص آبی؟ نام آن شبیه‌سازی دیجیتال را بنویس.", en: "Red pill or blue pill? Type the name of that digital simulation." },
    keywords: ["matrix", "neo", "greenrain"],
    logo: { text: "Edsel's", color: "#22C55E", font: "mono", anim: "logo-code" },
  },
  {
    id: "rainbow", icon: "🌈", kind: "effect",
    title: { fa: "حالت دیسکو", en: "Disco Mode" },
    subtitle: { fa: "رنگین‌کمان روی رابط", en: "Rainbow across the UI" },
    riddle: { fa: "هفت بار پشت سر هم روی نشان Edsel's بالای صفحه ضربه بزن.", en: "Tap the Edsel's wordmark at the top seven times in a row." },
    keywords: ["rainbow", "disco"],
    logo: { text: "Edsel's", color: "#F472B6", font: "edsel", anim: "logo-rainbow" },
  },

  /* ---------- 10 NEW GENERATED THEMES ---------- */
  {
    id: "cyberpunk", icon: "🌃", kind: "theme",
    title: { fa: "نایت سیتی ۲۰۷۷", en: "Night City 2077" },
    subtitle: { fa: "کروم، نئون و سایبرور", en: "Chrome, neon and cyberware" },
    riddle: { fa: "شهری که در آن بدنت را با کروم عوض می‌کنی و جانی سیلورهند در سرت زندگی می‌کند؛ سال آن را بنویس.", en: "A city where you trade flesh for chrome and Johnny Silverhand lives in your skull. Type its year." },
    keywords: ["cyberpunk", "2077", "nightcity", "netrunner"],
    overlay: {
      accent: "#FCEE0A", accent2: "#00F0FF",
      particles: ["◤", "◢", "▚", "░", "▓", "⌁"], particleCount: 26, effect: "glitch",
      centerGlyph: "⟁",
      quote: { fa: "«وقت آن است که افسانه شویم، ساموراییِ من.»", en: "\"Time to become a legend, samurai.\"" },
      label: "NIGHT CITY · ARASAKA",
    },
    logo: { text: "Edsel's", color: "#FCEE0A", font: "mono", suffix: "//2077", anim: "logo-glitch" },
  },
  {
    id: "strangerthings", icon: "🔮", kind: "theme",
    title: { fa: "دنیای وارونه", en: "The Upside Down" },
    subtitle: { fa: "هاوکینز · چراغ‌های الفبا", en: "Hawkins · Alphabet lights" },
    riddle: { fa: "بُعد تاریک و پر از خزه که زیر شهر هاوکینز نفس می‌کشد؛ نام وارونه‌اش را بنویس.", en: "The dark, spore-choked dimension breathing beneath Hawkins. Type its inverted name." },
    keywords: ["upsidedown", "strangerthings", "demogorgon", "vecna"],
    overlay: {
      accent: "#EF4444", accent2: "#F472B6",
      particles: ["✦", "•", "❋", "✧"], particleCount: 40, effect: "spore",
      centerGlyph: "⌬",
      quote: { fa: "«دوستان دروغ نمی‌گویند.»", en: "\"Friends don't lie.\"" },
      label: "HAWKINS, INDIANA · 1983",
    },
    logo: { text: "Edsel's", color: "#EF4444", font: "serif", anim: "logo-neon-red" },
  },
  {
    id: "interstellar", icon: "🌌", kind: "theme",
    title: { fa: "اینترستلار", en: "Interstellar" },
    subtitle: { fa: "گارگانتوا · تسراکت", en: "Gargantua · The Tesseract" },
    riddle: { fa: "سیاه‌چاله‌ای که یک ساعت کنارش برابر هفت سال روی زمین است؛ نام آن فیلم فضایی نولان را بنویس.", en: "A black hole where one hour equals seven years on Earth. Type the name of Nolan's space odyssey." },
    keywords: ["interstellar", "gargantua", "tesseract", "cooper", "murph"],
    overlay: {
      accent: "#FBBF24", accent2: "#38BDF8",
      particles: ["·", "✦", "✧", "•"], particleCount: 55, effect: "void",
      centerGlyph: "◍",
      quote: { fa: "«عشق تنها چیزی است که از زمان و مکان فراتر می‌رود.»", en: "\"Love is the one thing that transcends time and space.\"" },
      label: "ENDURANCE · LAZARUS MISSION",
    },
    logo: { text: "Edsel's", color: "#FBBF24", font: "serif", anim: "logo-orbit" },
  },
  {
    id: "joker", icon: "🃏", kind: "theme",
    title: { fa: "آشوب جوکر", en: "Joker's Chaos" },
    subtitle: { fa: "آرکهام · عامل آشوب", en: "Arkham · Agent of Chaos" },
    riddle: { fa: "دلقکی که با لبخند حکاکی‌شده کارت بازی می‌اندازد و می‌پرسد چرا این‌قدر جدی؟", en: "The clown with a carved smile who deals playing cards and asks: why so serious?" },
    keywords: ["joker", "arkham", "harley", "clownprince"],
    overlay: {
      accent: "#A855F7", accent2: "#22C55E",
      particles: ["🃏", "♠", "♦", "♣", "♥"], particleCount: 22, effect: "storm",
      centerGlyph: "☺",
      quote: { fa: "«اگر در کاری خوب باشی، هرگز رایگان انجامش نده.»", en: "\"If you're good at something, never do it for free.\"" },
      label: "GOTHAM · ARKHAM ASYLUM",
    },
    logo: { text: "Ǝdsel's", color: "#A855F7", font: "serif", anim: "logo-chaos" },
  },
  {
    id: "dune", icon: "🏜️", kind: "theme",
    title: { fa: "آراکیس · تلماسه", en: "Arrakis · Dune" },
    subtitle: { fa: "ادویه باید جاری بماند", en: "The spice must flow" },
    riddle: { fa: "سیاره‌ی صحرایی که کرم‌های غول‌پیکر و ادویه‌ی ملانژ دارد؛ نام دیگرش تلماسه است.", en: "The desert planet of colossal sandworms and melange spice — also called Dune." },
    keywords: ["dune", "arrakis", "spice", "fremen", "muaddib", "shaihulud"],
    overlay: {
      accent: "#F59E0B", accent2: "#FDE68A",
      particles: ["·", "∙", "•", "⋅"], particleCount: 70, effect: "storm",
      centerGlyph: "◈",
      quote: { fa: "«ترس، قاتلِ ذهن است. من با ترسم روبه‌رو خواهم شد.»", en: "\"Fear is the mind-killer. I will face my fear.\"" },
      label: "ARRAKIS · HOUSE ATREIDES",
    },
    logo: { text: "Edsel's", color: "#F59E0B", font: "serif", anim: "logo-sand" },
  },
  {
    id: "witcher", icon: "🐺", kind: "theme",
    title: { fa: "مکتب گرگ", en: "School of the Wolf" },
    subtitle: { fa: "کائر مورن · نشان گرگ", en: "Kaer Morhen · Wolf medallion" },
    riddle: { fa: "جهش‌یافته‌ای سفیدمو با دو شمشیر و مدال گرگ که هیولا شکار می‌کند؛ نام حرفه‌اش را بنویس.", en: "A white-haired mutant with two swords and a wolf medallion who hunts monsters. Type his profession." },
    keywords: ["witcher", "kaermorhen", "ciri", "yennefer", "toussaint"],
    overlay: {
      accent: "#E2E8F0", accent2: "#94A3B8",
      particles: ["ᛗ", "ᛉ", "ᛃ", "ᚨ", "ᛚ"], particleCount: 20, effect: "fog",
      centerGlyph: "🐺",
      quote: { fa: "«شر، شر است. کوچک‌تر، بزرگ‌تر، متوسط — فرقی نمی‌کند.»", en: "\"Evil is evil. Lesser, greater, middling — makes no difference.\"" },
      label: "KAER MORHEN · THE CONTINENT",
    },
    logo: { text: "Edsel's", color: "#E2E8F0", font: "serif", prefix: "ᛞ", anim: "logo-rune" },
  },
  {
    id: "bladerunner", icon: "🌆", kind: "theme",
    title: { fa: "بلید رانر ۲۰۴۹", en: "Blade Runner 2049" },
    subtitle: { fa: "باران نئون · تیرل کورپ", en: "Neon rain · Tyrell Corp" },
    riddle: { fa: "شکارچی همانندهای مصنوعی در لس‌آنجلس بارانی و نئونی سال ۲۰۴۹.", en: "The hunter of replicants in the rain-soaked neon Los Angeles of 2049." },
    keywords: ["bladerunner", "2049", "tyrell", "deckard", "voightkampff"],
    overlay: {
      accent: "#F97316", accent2: "#38BDF8",
      particles: ["│", "╎", "┆", "╷"], particleCount: 60, effect: "rain",
      centerGlyph: "◉",
      quote: { fa: "«همه‌ی آن لحظه‌ها گم خواهند شد، همچون اشک در باران.»", en: "\"All those moments will be lost in time, like tears in rain.\"" },
      label: "LOS ANGELES · 2049",
    },
    logo: { text: "Edsel's", color: "#F97316", font: "mono", anim: "logo-neon-orange" },
  },
  {
    id: "hollowknight", icon: "🦋", kind: "theme",
    title: { fa: "هالو نایت", en: "Hollow Knight" },
    subtitle: { fa: "هالونست · تهی و روح", en: "Hallownest · Void and Soul" },
    riddle: { fa: "پادشاهی زیرزمینی حشرات که شوالیه‌ای تهی با سوزن در آن قدم می‌زند.", en: "The subterranean insect kingdom where a hollow knight walks with a nail." },
    keywords: ["hollowknight", "hallownest", "grimm", "silksong", "nail"],
    overlay: {
      accent: "#93C5FD", accent2: "#C4B5FD",
      particles: ["✦", "•", "◦", "❉"], particleCount: 34, effect: "void",
      centerGlyph: "✤",
      quote: { fa: "«در تاریکی، هیچ صدایی جز طنین سوزن نیست.»", en: "\"No cost too great. No mind to think. No will to break.\"" },
      label: "HALLOWNEST · THE ABYSS",
    },
    logo: { text: "Edsel's", color: "#93C5FD", font: "serif", anim: "logo-void" },
  },
  {
    id: "deadpool", icon: "💀", kind: "theme",
    title: { fa: "ددپول", en: "Deadpool" },
    subtitle: { fa: "مزدور دهن‌لق · شکستن دیوار چهارم", en: "Merc with a Mouth · Fourth wall broken" },
    riddle: { fa: "مزدور قرمزپوش زخم‌خورده‌ای که مستقیم با تماشاگر حرف می‌زند و شوخی‌های بی‌ادبانه می‌کند.", en: "The scarred red-suited mercenary who talks straight to the audience and never shuts up." },
    keywords: ["deadpool", "wadewilson", "maximumeffort", "chimichanga", "fourthwall"],
    overlay: {
      accent: "#DC2626", accent2: "#F87171",
      particles: ["★", "✸", "✦", "!"], particleCount: 24, effect: "storm",
      centerGlyph: "☠",
      quote: { fa: "«حداکثر تلاش! ... صبر کن، این دیالوگ برای صحنه‌ی بعدی بود.»", en: "\"Maximum effort! ...wait, that line was for the next scene.\"" },
      label: "X-FORCE · MAXIMUM EFFORT",
    },
    logo: { text: "Edsel's", color: "#DC2626", font: "brand", suffix: "!", anim: "logo-bounce" },
  },
  {
    id: "attackontitan", icon: "🧱", kind: "theme",
    title: { fa: "حمله به تایتان", en: "Attack on Titan" },
    subtitle: { fa: "دیوار ماریا · گردان اکتشافی", en: "Wall Maria · Survey Corps" },
    riddle: { fa: "بشریتی که پشت سه دیوار عظیم پنهان شده و با تجهیزات مانور سه‌بعدی با غول‌ها می‌جنگد.", en: "Humanity hiding behind three colossal walls, fighting giants with omni-directional mobility gear." },
    keywords: ["attackontitan", "shingeki", "titan", "wallmaria", "scoutregiment"],
    overlay: {
      accent: "#84CC16", accent2: "#A16207",
      particles: ["⚔", "◤", "▲", "◣"], particleCount: 18, effect: "embers",
      centerGlyph: "🧱",
      quote: { fa: "«اگر بجنگی، شاید پیروز شوی؛ اگر نجنگی، هرگز.»", en: "\"If you win, you live. If you lose, you die. If you don't fight, you can't win.\"" },
      label: "SURVEY CORPS · WALL MARIA",
    },
    logo: { text: "Edsel's", color: "#84CC16", font: "brand", prefix: "⚔", anim: "logo-wings" },
  },

  /* ================= 26 NEW FULLY-DYNAMIC THEMES ================= */
  {
    id: "squidgame", icon: "🦑", kind: "theme",
    title: { fa: "بازی مرکب", en: "Squid Game" },
    subtitle: { fa: "چراغ سبز، چراغ قرمز · شماره ۴۵۶", en: "Green light, red light · Player 456" },
    riddle: { fa: "بازی کره‌ای مرگباری با عروسک خزنده، آب‌نبات دالگونا و نگهبانان صورتی‌پوش نقاب‌دار.", en: "The deadly Korean game with a creeping doll, dalgona candy, and pink-suited masked guards." },
    keywords: ["squidgame", "456", "redlightgreenlight", "dalgona", "gihun"],
    overlay: {
      accent: "#FF2E88", accent2: "#00C4A7",
      particles: ["○", "△", "□", "🦑", "●"], particleCount: 30, effect: "spore",
      centerGlyph: "◉",
      quote: { fa: "«چراغ سبز... چراغ قرمز!»", en: "\"Green light... Red light!\"" },
      label: "PLAYER 456 · THE FRONT MAN",
    },
    logo: { text: "Edsel's", color: "#FF2E88", font: "brand", prefix: "◯△□", anim: "logo-squid" },
  },
  {
    id: "peakyblinderstheme", icon: "🎩", kind: "theme",
    title: { fa: "پیکی بلایندرز", en: "Peaky Blinders" },
    subtitle: { fa: "بیرمنگام ۱۹۲۰ · خانواده‌ی شلبی", en: "Birmingham 1920s · Shelby Company" },
    riddle: { fa: "گنگ بیرمنگامی با کلاه‌های تیغه‌دار در دهه‌ی بیست، به رهبری تامی شلبی.", en: "The Birmingham gang with razor-blade caps in the 1920s, led by Tommy Shelby." },
    keywords: ["peakyblinderstheme", "smallheath", "byorderof", "shelbycompany"],
    overlay: {
      accent: "#E9C46A", accent2: "#B08968",
      particles: ["·", "∙", "•"], particleCount: 45, effect: "fog",
      centerGlyph: "🎩",
      quote: { fa: "«به فرمان پیکی بلایندرز.»", en: "\"By order of the Peaky Blinders.\"" },
      label: "SMALL HEATH · SHELBY LTD",
    },
    logo: { text: "Edsel's", color: "#E9C46A", font: "serif", anim: "logo-ember-glow" },
  },
  {
    id: "duneii", icon: "🪱", kind: "theme",
    title: { fa: "تلماسه: بخش دوم", en: "Dune: Part Two" },
    subtitle: { fa: "آراکیس · لیسان الغیب", en: "Arrakis · Lisan al-Gaib" },
    riddle: { fa: "پیامبر صحرا که بر کرم شنی سوار شد و فِرمن‌ها را رهبری کرد؛ نام او پل آترایدیس است.", en: "The desert messiah who rode a sandworm and led the Fremen; his name is Paul Atreides." },
    keywords: ["paulatreides", "lisanalgaib", "duneii", "chani", "stilgar"],
    overlay: {
      accent: "#E8B04B", accent2: "#7C3AED",
      particles: ["·", "∙", "•", "⋅", "‧"], particleCount: 85, effect: "storm",
      centerGlyph: "𓂀",
      quote: { fa: "«راه بلند و دشوار است، اما ادویه جاری خواهد ماند.»", en: "\"The sleeper must awaken. Long live the fighters.\"" },
      label: "ARRAKEEN · FREMEN JIHAD",
    },
    logo: { text: "Edsel's", color: "#E8B04B", font: "serif", anim: "logo-sand" },
  },
  {
    id: "oppenheimer", icon: "☢️", kind: "theme",
    title: { fa: "اوپنهایمر", en: "Oppenheimer" },
    subtitle: { fa: "پروژه‌ی منهتن · ترینیتی", en: "The Manhattan Project · Trinity" },
    riddle: { fa: "پدر بمب اتم که پس از انفجار ترینیتی گفت اکنون من مرگ شده‌ام، ویرانگر جهان‌ها.", en: "The father of the atomic bomb who quoted: now I am become Death, destroyer of worlds." },
    keywords: ["oppenheimer", "manhattanproject", "trinity", "destroyerofworlds", "losalamos"],
    overlay: {
      accent: "#FF7A18", accent2: "#FFD166",
      particles: ["◦", "•", "○", "◌"], particleCount: 40, effect: "embers",
      centerGlyph: "⚛",
      quote: { fa: "«اکنون من مرگ شده‌ام، ویرانگرِ جهان‌ها.»", en: "\"Now I am become Death, the destroyer of worlds.\"" },
      label: "LOS ALAMOS · TRINITY TEST",
    },
    logo: { text: "Edsel's", color: "#FF7A18", font: "serif", anim: "logo-atom" },
  },
  {
    id: "tron", icon: "🏍️", kind: "theme",
    title: { fa: "ترون: میراث", en: "Tron: Legacy" },
    subtitle: { fa: "شبکه · نور دیجیتال", en: "The Grid · Digital light" },
    riddle: { fa: "دنیای دیجیتالی درون رایانه با موتورهای نوری و دیسک‌های شناسه؛ نام آن گرید است.", en: "The digital world inside the computer with light cycles and identity discs; it's called the Grid." },
    keywords: ["tron", "thegrid", "lightcycle", "clu", "flynn"],
    overlay: {
      accent: "#00E5FF", accent2: "#FF6D00",
      particles: ["│", "─", "┼", "╬", "▮"], particleCount: 44, effect: "glitch",
      centerGlyph: "⬡",
      quote: { fa: "«من به شبکه می‌جنگم؛ برای کاربران.»", en: "\"I fight for the Users.\"" },
      label: "THE GRID · ENCOM SYSTEM",
    },
    logo: { text: "Edsel's", color: "#00E5FF", font: "mono", anim: "logo-tron" },
  },
  {
    id: "johnwick", icon: "🐶", kind: "theme",
    title: { fa: "جان ویک", en: "John Wick" },
    subtitle: { fa: "هتل کانتیننتال · سکه‌ی طلا", en: "The Continental · Gold coins" },
    riddle: { fa: "قاتل افسانه‌ای که به خاطر توله‌سگش انتقام گرفت؛ او را بابا یاگا صدا می‌زنند.", en: "The legendary assassin who came back for his puppy; they call him Baba Yaga." },
    keywords: ["johnwick", "babayaga", "continental", "highTable", "goldcoin"],
    overlay: {
      accent: "#00B7C2", accent2: "#E63946",
      particles: ["│", "╎", "┆"], particleCount: 55, effect: "rain",
      centerGlyph: "⛧",
      quote: { fa: "«فکر کردی برگشتم؟ کاملاً برگشتم.»", en: "\"People keep asking if I'm back. Yeah, I'm thinking I'm back.\"" },
      label: "THE CONTINENTAL · HIGH TABLE",
    },
    logo: { text: "Edsel's", color: "#00B7C2", font: "mono", anim: "logo-neon-cyan" },
  },
  {
    id: "gmeninblack", icon: "🕶️", kind: "theme",
    title: { fa: "مردان سیاه‌پوش", en: "Men in Black" },
    subtitle: { fa: "نئورالایزر · بیگانگان زمین", en: "The Neuralyzer · Aliens on Earth" },
    riddle: { fa: "مأموران کت‌مشکی و عینک‌آفتابی که خاطرات را با فلاش پاک می‌کنند و بیگانه‌ها را می‌پایند.", en: "The black-suited, sunglassed agents who flash away memories and police the aliens on Earth." },
    keywords: ["meninblack", "mib", "neuralyzer", "agentj", "agentk"],
    overlay: {
      accent: "#111827", accent2: "#22C55E",
      particles: ["✦", "•", "◦", "✧"], particleCount: 34, effect: "void",
      centerGlyph: "👁",
      quote: { fa: "«به این نور نگاه کن...»", en: "\"Look right here, please.\"" },
      label: "DIVISION 6 · THE GALAXY",
    },
    logo: { text: "Edsel's", color: "#22C55E", font: "mono", anim: "logo-flash" },
  },
  {
    id: "avatar", icon: "🌿", kind: "theme",
    title: { fa: "آواتار", en: "Avatar" },
    subtitle: { fa: "پاندورا · نائوی", en: "Pandora · The Na'vi" },
    riddle: { fa: "سیاره‌ی جنگلی درخشانی که بومیانش آبی‌پوست بلندقامتند و درخت روح دارند؛ نامش پاندوراست.", en: "The glowing forest moon whose blue-skinned natives revere the Tree of Souls; it's called Pandora." },
    keywords: ["avatar", "pandora", "navi", "jakesully", "unobtanium"],
    overlay: {
      accent: "#4CC9F0", accent2: "#B5179E",
      particles: ["✿", "❀", "•", "✦", "❁"], particleCount: 48, effect: "spore",
      centerGlyph: "❋",
      quote: { fa: "«من تو را می‌بینم.»", en: "\"I see you.\"" },
      label: "PANDORA · OMATIKAYA CLAN",
    },
    logo: { text: "Edsel's", color: "#4CC9F0", font: "serif", anim: "logo-bioluminescent" },
  },
  {
    id: "madmax", icon: "🏜️", kind: "theme",
    title: { fa: "مکس دیوانه", en: "Mad Max: Fury Road" },
    subtitle: { fa: "بیابان · وار بویز", en: "The Wasteland · War Boys" },
    riddle: { fa: "دنیای پساآخرالزمانی بیابانی با ماشین‌های دیوانه و ایمورتان جو؛ نام قهرمانش مکس است.", en: "The post-apocalyptic desert of insane vehicles and Immortan Joe; the hero's name is Max." },
    keywords: ["madmax", "furyroad", "immortanjoe", "furiosa", "warboys"],
    overlay: {
      accent: "#FF6B00", accent2: "#D62828",
      particles: ["·", "∙", "•", "⋅"], particleCount: 75, effect: "storm",
      centerGlyph: "☠",
      quote: { fa: "«امروز به والهالا وارد می‌شویم! درخشان و براق!»", en: "\"Witness me! I live, I die, I live again!\"" },
      label: "THE WASTELAND · CITADEL",
    },
    logo: { text: "Edsel's", color: "#FF6B00", font: "brand", anim: "logo-dustglow" },
  },
  {
    id: "arcane", icon: "💎", kind: "theme",
    title: { fa: "آرکین", en: "Arcane" },
    subtitle: { fa: "پیلتوور و زان · هیمرینگ", en: "Piltover & Zaun · Hextech" },
    riddle: { fa: "انیمیشنی درباره‌ی دو خواهر در شهر بالا و شهر زیرزمینی، جینکس و وای؛ نامش آرکین است.", en: "The animated tale of two sisters across the upper and undercity, Jinx and Vi; it's called Arcane." },
    keywords: ["arcane", "jinx", "piltover", "zaun", "hextech"],
    overlay: {
      accent: "#00D9F5", accent2: "#F72585",
      particles: ["◆", "◇", "✦", "❖"], particleCount: 40, effect: "void",
      centerGlyph: "❈",
      quote: { fa: "«فکر می‌کردی من دیوانه‌ام، درست است؟»", en: "\"You thought I'd be different? Powerful?\"" },
      label: "ZAUN · THE UNDERCITY",
    },
    logo: { text: "Edsel's", color: "#F72585", font: "brand", anim: "logo-hextech" },
  },
  {
    id: "narcos", icon: "🌱", kind: "theme",
    title: { fa: "نارکوس", en: "Narcos" },
    subtitle: { fa: "مِدِیین · کارتل کلمبیا", en: "Medellín · The Cartel" },
    riddle: { fa: "سریالی درباره‌ی پادشاه کوکائین کلمبیا؛ سکه یا شلیک؟ نام او پابلو اسکوبار است.", en: "The series about Colombia's cocaine king; plata o plomo. His name is Pablo Escobar." },
    keywords: ["narcos", "escobar", "medellin", "plataoplomo", "cartel"],
    overlay: {
      accent: "#3DDC84", accent2: "#FFB703",
      particles: ["✦", "•", "◦"], particleCount: 36, effect: "fog",
      centerGlyph: "❦",
      quote: { fa: "«پول یا سرب؟ (پلاتا او پلومو)»", en: "\"Plata o plomo. Silver or lead.\"" },
      label: "MEDELLÍN · THE DEA",
    },
    logo: { text: "Edsel's", color: "#3DDC84", font: "serif", anim: "logo-ember-glow" },
  },
  {
    id: "vikings", icon: "🪓", kind: "theme",
    title: { fa: "وایکینگ‌ها", en: "Vikings" },
    subtitle: { fa: "کاتگات · والهالا", en: "Kattegat · Valhalla" },
    riddle: { fa: "جنگجویان اسکاندیناوی که به والهالا و ادین باور دارند؛ نام قهرمانشان راگنار لاثبروک است.", en: "The Norse raiders who believe in Odin and Valhalla; their hero is Ragnar Lothbrok." },
    keywords: ["vikings", "ragnar", "valhalla", "kattegat", "odin"],
    overlay: {
      accent: "#A7C4BC", accent2: "#5E503F",
      particles: ["ᚠ", "ᚢ", "ᚦ", "ᚨ", "ᚱ", "ᚲ"], particleCount: 26, effect: "fog",
      centerGlyph: "ᛝ",
      quote: { fa: "«والهالا! به آغوش ادین می‌رویم.»", en: "\"Odin will receive us! Valhalla awaits!\"" },
      label: "KATTEGAT · SONS OF RAGNAR",
    },
    logo: { text: "Edsel's", color: "#A7C4BC", font: "serif", prefix: "ᚱ", anim: "logo-rune" },
  },
  {
    id: "spongebob", icon: "🧽", kind: "theme",
    title: { fa: "باب اسفنجی", en: "SpongeBob" },
    subtitle: { fa: "بیکینی باتم · کرابی پتی", en: "Bikini Bottom · Krabby Patty" },
    riddle: { fa: "اسفنج زردی که در آناناسی زیر دریا زندگی می‌کند و برای آقای خرچنگ کار می‌کند.", en: "The yellow sponge who lives in a pineapple under the sea and works for Mr. Krabs." },
    keywords: ["spongebob", "bikinibottom", "krabbypatty", "pineapple"],
    overlay: {
      accent: "#FFE600", accent2: "#00C2FF",
      particles: ["○", "◦", "•", "°", "˚"], particleCount: 55, effect: "void",
      centerGlyph: "🧽",
      quote: { fa: "«من آماده‌ام! من آماده‌ام!»", en: "\"I'm ready! I'm ready!\"" },
      label: "BIKINI BOTTOM · KRUSTY KRAB",
    },
    logo: { text: "Edsel's", color: "#FFE600", font: "brand", anim: "logo-bubble" },
  },
  {
    id: "rickmorty", icon: "🛸", kind: "theme",
    title: { fa: "ریک و مورتی", en: "Rick and Morty" },
    subtitle: { fa: "بعد C-137 · پورتال سبز", en: "Dimension C-137 · Green portals" },
    riddle: { fa: "دانشمند دیوانه‌ی الکلی و نوه‌اش که با تفنگ پورتال سبز بین ابعاد سفر می‌کنند.", en: "The drunk mad scientist and his grandson who portal across dimensions with a green gun." },
    keywords: ["rickmorty", "portalgun", "mortyc137"],
    overlay: {
      accent: "#00FF9C", accent2: "#37E2FF",
      particles: ["◉", "◎", "○", "⊙"], particleCount: 30, effect: "glitch",
      centerGlyph: "◉",
      quote: { fa: "«ویبا لوبا داب داب!»", en: "\"Wubba lubba dub dub!\"" },
      label: "DIMENSION C-137 · THE CITADEL",
    },
    logo: { text: "Edsel's", color: "#00FF9C", font: "mono", anim: "logo-portal" },
  },
  {
    id: "cybermatrix4", icon: "💠", kind: "theme",
    title: { fa: "ماتریکس: رستاخیزها", en: "The Matrix Resurrections" },
    subtitle: { fa: "بازگشت به شبیه‌سازی · مودال", en: "Back into the sim · The Modal" },
    riddle: { fa: "نسخه‌ی چهارم فیلمی درباره‌ی نئو که به دنیای شبیه‌سازی‌شده بازمی‌گردد؛ قرص را انتخاب کن.", en: "The fourth film about Neo returning to the simulation; choose the pill and resurrect." },
    keywords: ["resurrections", "matrix4", "themodal", "neoreturns", "analyst"],
    overlay: {
      accent: "#00FFC6", accent2: "#0077FF",
      particles: ["0", "1", "リ", "ハ", "ネ", "ヲ"], particleCount: 50, effect: "rain",
      centerGlyph: "⧉",
      quote: { fa: "«پس از این‌همه سال، دوباره به خانه بازگشتی.»", en: "\"After all these years, back where you started.\"" },
      label: "THE MODAL · IO CITY",
    },
    logo: { text: "Edsel's", color: "#00FFC6", font: "mono", anim: "logo-code" },
  },
  {
    id: "harrypotter", icon: "⚡", kind: "theme",
    title: { fa: "هری پاتر", en: "Harry Potter" },
    subtitle: { fa: "هاگوارتز · جادو", en: "Hogwarts · Wizardry" },
    riddle: { fa: "پسری با اسکار رعدی روی پیشانی که به مدرسه‌ی جادوگری هاگوارتز رفت؛ لوموس!", en: "The boy with a lightning scar who attended the Hogwarts school of wizardry; Lumos!" },
    keywords: ["harrypotter", "hogwarts", "lumos", "expelliarmus", "voldemort"],
    overlay: {
      accent: "#D4AF37", accent2: "#7B2D26",
      particles: ["✦", "✧", "⋆", "✩", "★"], particleCount: 44, effect: "void",
      centerGlyph: "⚡",
      quote: { fa: "«لوموس. نور را روشن می‌کنم.»", en: "\"It does not do to dwell on dreams and forget to live.\"" },
      label: "HOGWARTS · GRYFFINDOR",
    },
    logo: { text: "Edsel's", color: "#D4AF37", font: "serif", prefix: "⚡", anim: "logo-magic" },
  },
  {
    id: "pirates", icon: "🏴‍☠️", kind: "theme",
    title: { fa: "دزدان دریایی کارائیب", en: "Pirates of the Caribbean" },
    subtitle: { fa: "مروارید سیاه · کاپیتان جک", en: "The Black Pearl · Captain Jack" },
    riddle: { fa: "کاپیتان دزد دریایی مستی که کشتی مروارید سیاه داشت؛ چرا رام تمام شد؟", en: "The tipsy pirate captain of the Black Pearl; why is the rum always gone?" },
    keywords: ["piratescaribbean", "jacksparrow", "blackpearl", "whyistherumgone", "davyjones"],
    overlay: {
      accent: "#C9A227", accent2: "#1B3A4B",
      particles: ["·", "∙", "•", "⋅"], particleCount: 60, effect: "storm",
      centerGlyph: "☠",
      quote: { fa: "«چرا رام همیشه تمام می‌شود؟»", en: "\"Why is the rum always gone?\"" },
      label: "THE BLACK PEARL · TORTUGA",
    },
    logo: { text: "Edsel's", color: "#C9A227", font: "serif", anim: "logo-dustglow" },
  },
  {
    id: "cyberghost", icon: "👻", kind: "theme",
    title: { fa: "شبح در پوسته", en: "Ghost in the Shell" },
    subtitle: { fa: "بخش ۹ · سایبورگ", en: "Section 9 · Cyborg" },
    riddle: { fa: "انیمه‌ی سایبرپانکی درباره‌ی مأمور سایبورگی به نام ماکوتو کوساناگی و روح درون پوسته.", en: "The cyberpunk anime about a cyborg agent named Motoko Kusanagi and the ghost within the shell." },
    keywords: ["ghostintheshell", "kusanagi", "section9", "puppetmaster", "motoko"],
    overlay: {
      accent: "#FF3CAC", accent2: "#2B86C5",
      particles: ["0", "1", "▚", "▞", "░"], particleCount: 46, effect: "glitch",
      centerGlyph: "⊚",
      quote: { fa: "«اگر ما ارواحی درون پوسته‌ایم، پس مرزِ انسان کجاست؟»", en: "\"If a technological feat is possible, man will do it.\"" },
      label: "SECTION 9 · NEW PORT CITY",
    },
    logo: { text: "Edsel's", color: "#FF3CAC", font: "mono", anim: "logo-glitch" },
  },
  {
    id: "twinpeaks", icon: "☕", kind: "theme",
    title: { fa: "توین پیکس", en: "Twin Peaks" },
    subtitle: { fa: "اتاق قرمز · جغد‌ها", en: "The Red Room · The owls" },
    riddle: { fa: "سریال مرموز لینچ درباره‌ی مرگ لورا پالمر و اتاق قرمز؛ جغدها آنی که به نظر می‌رسند نیستند.", en: "Lynch's mystery about the death of Laura Palmer and the Red Room; the owls are not what they seem." },
    keywords: ["twinpeaks", "laurapalmer", "redroom", "blacklodge", "damngoodcoffee"],
    overlay: {
      accent: "#E63946", accent2: "#2A9D8F",
      particles: ["◣", "◢", "◤", "◥"], particleCount: 32, effect: "void",
      centerGlyph: "▣",
      quote: { fa: "«جغدها آنی که به نظر می‌رسند نیستند.»", en: "\"The owls are not what they seem.\"" },
      label: "TWIN PEAKS · THE BLACK LODGE",
    },
    logo: { text: "Edsel's", color: "#E63946", font: "serif", anim: "logo-zigzag" },
  },
  {
    id: "invincible", icon: "🩸", kind: "theme",
    title: { fa: "شکست‌ناپذیر", en: "Invincible" },
    subtitle: { fa: "مارک گریسون · ویلترومایت‌ها", en: "Mark Grayson · The Viltrumites" },
    riddle: { fa: "انیمیشنی درباره‌ی پسر ابرقهرمانی که پدرش امنی‌من است؛ فکر می‌کردی بعدش چه اتفاقی می‌افتد مارک؟", en: "The animated show about a superhero teen whose father is Omni-Man; think, Mark!" },
    keywords: ["invincible", "omniman", "markgrayson", "viltrum", "thinkmark"],
    overlay: {
      accent: "#3A86FF", accent2: "#D90429",
      particles: ["✦", "★", "✸", "!"], particleCount: 28, effect: "storm",
      centerGlyph: "✦",
      quote: { fa: "«فکر کن مارک! بعد از پانصد سال چه چیزی برایت می‌ماند؟»", en: "\"Think, Mark! What will you have after 500 years?\"" },
      label: "VILTRUM EMPIRE · EARTH",
    },
    logo: { text: "Edsel's", color: "#3A86FF", font: "brand", anim: "logo-bounce" },
  },
  {
    id: "cowboybebop", icon: "🎷", kind: "theme",
    title: { fa: "کابوی بیباپ", en: "Cowboy Bebop" },
    subtitle: { fa: "سفینه‌ی بیباپ · جز و بلوز", en: "The Bebop · Jazz & blues" },
    riddle: { fa: "انیمه‌ی جایزه‌بگیرهای فضایی با جز نواز و سفینه‌ی بیباپ؛ می‌بینمت کابوی فضایی.", en: "The space bounty-hunter anime with a jazzy score and the ship Bebop; see you, space cowboy." },
    keywords: ["cowboybebop", "bebopship", "seeyou", "spikefaye"],
    overlay: {
      accent: "#FFD23F", accent2: "#3BCEAC",
      particles: ["♪", "♩", "♫", "✦", "•"], particleCount: 34, effect: "void",
      centerGlyph: "♫",
      quote: { fa: "«می‌بینمت، کابوی فضایی...»", en: "\"See you, space cowboy...\"" },
      label: "THE BEBOP · SESSION #1",
    },
    logo: { text: "Edsel's", color: "#FFD23F", font: "mono", anim: "logo-jazz" },
  },
  {
    id: "severance", icon: "🧠", kind: "theme",
    title: { fa: "قطع رابطه", en: "Severance" },
    subtitle: { fa: "لومون · اینی و اوتی", en: "Lumon · Innie & Outie" },
    riddle: { fa: "سریالی درباره‌ی کارمندانی که خاطرات کار و زندگی‌شان جراحی و جدا شده؛ نام شرکت لومون است.", en: "The show about employees whose work and life memories are surgically severed; the company is Lumon." },
    keywords: ["severance", "lumon", "innie", "macrodata", "kier"],
    overlay: {
      accent: "#7FDBFF", accent2: "#B3E5D1",
      particles: ["·", "∙", "•", "◦"], particleCount: 40, effect: "fog",
      centerGlyph: "◫",
      quote: { fa: "«لطفاً از تجربه‌ی خود لذت ببرید، به یک اندازه.»", en: "\"Please enjoy each number equally.\"" },
      label: "LUMON INDUSTRIES · MDR",
    },
    logo: { text: "Edsel's", color: "#7FDBFF", font: "mono", anim: "logo-clinical" },
  },
  {
    id: "cyberpsycho", icon: "🌸", kind: "theme",
    title: { fa: "ساکورا · هانامی", en: "Sakura Hanami" },
    subtitle: { fa: "شکوفه‌های گیلاس · ژاپن", en: "Cherry blossoms · Japan" },
    riddle: { fa: "جشن تماشای شکوفه‌های صورتی گیلاس در بهار ژاپن؛ نام درخت آن ساکورا است.", en: "The spring festival of viewing pink cherry blossoms in Japan; the tree is called sakura." },
    keywords: ["sakura", "hanami", "cherryblossom", "japan", "spring"],
    overlay: {
      accent: "#FF8FB1", accent2: "#FFC2D1",
      particles: ["🌸", "❀", "✿", "•", "❁"], particleCount: 55, effect: "spore",
      centerGlyph: "🌸",
      quote: { fa: "«شکوفه‌ها می‌ریزند، اما بهار باز می‌گردد.»", en: "\"The blossoms fall, but spring always returns.\"" },
      label: "HANAMI · KYOTO",
    },
    logo: { text: "Edsel's", color: "#FF8FB1", font: "serif", prefix: "🌸", anim: "logo-petal" },
  },
  {
    id: "aurora", icon: "🌌", kind: "theme",
    title: { fa: "شفق قطبی", en: "Aurora Borealis" },
    subtitle: { fa: "نور شمالی · قطب", en: "The Northern Lights · Poles" },
    riddle: { fa: "پرده‌های سبز و بنفش نوری که در آسمان قطب شمال می‌رقصند؛ نام لاتین آن آئورورا است.", en: "The dancing green and violet curtains of light in the polar sky; its Latin name is Aurora." },
    keywords: ["aurora", "borealis", "northernlights", "polarlights", "shafagh"],
    overlay: {
      accent: "#39FF14", accent2: "#9D4EDD",
      particles: ["✦", "•", "✧", "⋆", "∗"], particleCount: 60, effect: "void",
      centerGlyph: "✦",
      quote: { fa: "«آسمان قطبی، آتش خاموشِ رنگ‌هاست.»", en: "\"The polar sky is a silent fire of colors.\"" },
      label: "AURORA BOREALIS · 68°N",
    },
    logo: { text: "Edsel's", color: "#39FF14", font: "serif", anim: "logo-aurora" },
  },
  {
    id: "vaporwave", icon: "📼", kind: "theme",
    title: { fa: "ویپورویو", en: "Vaporwave" },
    subtitle: { fa: "زیبایی‌شناسی ۸۰ · نئون صورتی", en: "80s aesthetic · Pink neon" },
    riddle: { fa: "سبک هنری رترویی با نئون صورتی و آبی، مجسمه‌های یونانی و شبکه‌های بی‌نهایت؛ نامش با بخار شروع می‌شود.", en: "The retro art style with pink-blue neon, Greek busts and endless grids; its name starts with vapor." },
    keywords: ["vaporwave", "aesthetic", "retrowave", "synthwave", "80s"],
    overlay: {
      accent: "#FF71CE", accent2: "#01CDFE",
      particles: ["▲", "◆", "■", "◇", "△"], particleCount: 40, effect: "glitch",
      centerGlyph: "卂",
      quote: { fa: "«ﾑﾑçå毛 ﾑ乇丂ｲﾑ乇ｲﾉ丂 · گذشته آینده است.»", en: "\"A E S T H E T I C · the past is the future.\"" },
      label: "V A P O R W A V E · MMXX",
    },
    logo: { text: "Edsel's", color: "#FF71CE", font: "mono", anim: "logo-vapor" },
  },
];

export const ACTIVE_MAP: Record<string, ActiveEgg> = Object.fromEntries(
  ACTIVE_EGGS.map((e) => [e.id, e])
);

/** ids of the 10 themes rendered by the generic overlay engine */
export const GENERATED_THEMES = ACTIVE_EGGS.filter((e) => e.overlay).map((e) => e.id);
